global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "Gateway"
    static_configs:
      - targets:
          - api-gateway:3000

  - job_name: "service-a"
    static_configs:
      - targets:
          - service-a:3001

  - job_name: "service-b"
    static_configs:
      - targets:
          - service-b:3002