global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets: ["app:5000"]

  - job_name: "mongo"
    static_configs:
      - targets: ["db-exporter:9216"]