name: API Testing & Coverage

# Triggers for the workflow
on:
  # Run on push events, but only for files in the api directory
  push:
    paths:
      - 'api/**'
  # Run on pull requests to main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      # Install dependencies
      - name: Install Dependencies
        run: npm ci
        working-directory: ./api
      
      # Run Jest tests with coverage using ArtiomTr's action
      - name: Run Tests
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./api
          test-script: npm test
          threshold: 80 # 80% code coverage threshold
          package-manager: npm
          coverage-file: ./coverage/coverage-final.json