name: CI - Service B

on:
  push:
    paths:
      - 'services/service-a/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm i
        working-directory: ./services/service-b

      - name: Run tests
        run: npm test
        working-directory: ./services/service-b
      - name: Run ESLint
        run: npm run lint
        working-directory: ./services/service-b